import type { SeedQuestion } from "./types";

/**
 * Seed Mathematics bank (original items for MVP assembly).
 * Metadata uses CAPS cognitive levels — not Bloom's.
 */
export const SEED_MATHS_QUESTIONS: SeedQuestion[] = [
  {
    id: "maths-g12-alg-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Algebra and equations",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText:
      "Write down the discriminant formula used to determine the nature of the roots of a quadratic equation ax² + bx + c = 0.",
    memoAnswer: "Δ = b² − 4ac",
    markingPoints: ["Correct discriminant formula"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-alg-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Algebra and equations",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText: "Solve for x: 2x² − 5x − 3 = 0.",
    memoAnswer: "x = 3 or x = −1/2",
    markingPoints: ["Correct factorisation or quadratic formula", "Both roots"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-alg-03",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Algebra and equations",
    difficulty: "hard",
    marks: 5,
    cognitiveLevel: "complex_procedure",
    questionText:
      "Determine the values of k for which the equation x² − (k + 1)x + k = 0 has real and equal roots.",
    memoAnswer: "k = 1 only (from Δ = 0 → (k+1)² − 4k = 0 → k² − 2k + 1 = 0 → (k−1)² = 0)",
    markingPoints: ["Set discriminant to zero", "Expand and simplify", "Solve for k"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-fn-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Functions and graphs",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText: "State the domain of f(x) = √(x − 3).",
    memoAnswer: "x ≥ 3",
    markingPoints: ["Correct inequality for domain"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-fn-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Functions and graphs",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText:
      "Given f(x) = 2x² − 8x + 5, determine the coordinates of the turning point of f.",
    memoAnswer: "(2; −3)",
    markingPoints: ["x = −b/(2a) = 2", "f(2) = −3", "Coordinates stated"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-fn-03",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Functions and graphs",
    difficulty: "hard",
    marks: 6,
    cognitiveLevel: "problem_solving",
    questionText:
      "A quadratic f has a minimum value of −4 at x = 1 and passes through (0; −1). Determine f(x).",
    memoAnswer: "f(x) = 3(x − 1)² − 4 = 3x² − 6x − 1",
    markingPoints: ["Vertex form with a unknown", "Use point to find a", "Expanded form"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-seq-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Patterns and sequences",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText: "Write down the formula for the nth term of an arithmetic sequence.",
    memoAnswer: "Tn = a + (n − 1)d",
    markingPoints: ["Correct formula"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-seq-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Patterns and sequences",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText: "The first term of a geometric sequence is 5 and the common ratio is 2. Calculate T6.",
    memoAnswer: "T6 = 5 × 2⁵ = 160",
    markingPoints: ["Correct formula Tn = ar^(n−1)", "Substitution", "Answer"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-fin-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Finance and growth",
    difficulty: "medium",
    marks: 5,
    cognitiveLevel: "routine_procedure",
    questionText:
      "R12 000 is invested for 4 years at 8% p.a. compounded annually. Calculate the accumulated amount.",
    memoAnswer: "A = 12000(1,08)⁴ ≈ R16 325,87",
    markingPoints: ["Correct compound interest formula", "Substitution", "Rounded answer"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-fin-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Finance and growth",
    difficulty: "hard",
    marks: 6,
    cognitiveLevel: "complex_procedure",
    questionText:
      "A loan of R80 000 is repaid with equal monthly instalments over 5 years at 12% p.a. compounded monthly. Calculate the monthly instalment (to the nearest rand).",
    memoAnswer: "Use present-value annuity formula; x ≈ R1 778",
    markingPoints: ["i = 0,01; n = 60", "Correct PV formula", "Solve for x", "Rounded answer"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-ag-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Analytical geometry",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText: "State the distance formula between points A(x₁; y₁) and B(x₂; y₂).",
    memoAnswer: "AB = √[(x₂ − x₁)² + (y₂ − y₁)²]",
    markingPoints: ["Correct distance formula"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-ag-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Analytical geometry",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText: "Determine the midpoint of A(−2; 5) and B(6; −1).",
    memoAnswer: "M(2; 2)",
    markingPoints: ["Midpoint formula", "Both coordinates"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-ag-03",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Analytical geometry",
    difficulty: "hard",
    marks: 6,
    cognitiveLevel: "complex_procedure",
    questionText:
      "A circle has equation x² + y² − 6x + 4y − 12 = 0. Determine the centre and radius.",
    memoAnswer: "Centre (3; −2), radius 5",
    markingPoints: ["Complete the square", "Centre", "Radius"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-ag-04",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Analytical geometry",
    difficulty: "hard",
    marks: 7,
    cognitiveLevel: "problem_solving",
    questionText:
      "Find the equation of the tangent to the circle x² + y² = 25 at the point (3; 4).",
    memoAnswer: "3x + 4y = 25",
    markingPoints: ["Radius perpendicular to tangent", "Gradient of radius", "Tangent equation"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-trig-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Trigonometry",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText: "Write down the identity for sin²θ + cos²θ.",
    memoAnswer: "sin²θ + cos²θ = 1",
    markingPoints: ["Correct identity"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-trig-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Trigonometry",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText: "If sin θ = 3/5 and θ is acute, determine cos θ without a calculator.",
    memoAnswer: "cos θ = 4/5",
    markingPoints: ["Pythagoras / identity", "Positive root for acute θ"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-trig-03",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Trigonometry",
    difficulty: "hard",
    marks: 6,
    cognitiveLevel: "complex_procedure",
    questionText: "Solve for θ ∈ [0°; 360°]: 2 cos θ = 1.",
    memoAnswer: "θ = 60° or θ = 300°",
    markingPoints: ["cos θ = 1/2", "Both solutions in interval"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-trig-04",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Trigonometry",
    difficulty: "hard",
    marks: 6,
    cognitiveLevel: "problem_solving",
    questionText:
      "Prove that (sin 2θ)/(1 + cos 2θ) = tan θ for all θ where the expressions are defined.",
    memoAnswer:
      "LHS = (2 sin θ cos θ)/(2 cos² θ) = sin θ / cos θ = tan θ = RHS",
    markingPoints: ["Double-angle identities", "Simplify", "Conclusion"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-euc-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Euclidean geometry",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText:
      "Complete: The angle subtended by an arc at the centre of a circle is … the angle subtended by the same arc at the circumference.",
    memoAnswer: "twice / double",
    markingPoints: ["Correct theorem statement"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-euc-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Euclidean geometry",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText:
      "In △ABC, D is on BC such that AD ⊥ BC. Given AB = 13, BD = 5 and DC = 9, calculate AD.",
    memoAnswer: "AD = 12 (from Pythagoras in △ABD)",
    markingPoints: ["Identify right triangle", "Pythagoras", "Answer"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-euc-03",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Euclidean geometry",
    difficulty: "hard",
    marks: 6,
    cognitiveLevel: "complex_procedure",
    questionText:
      "O is the centre of a circle. Chord AB subtends ∠AOB = 80° at the centre. Calculate the size of ∠ACB where C is a point on the major arc.",
    memoAnswer: "∠ACB = 40° (angle at centre = 2 × angle at circumference)",
    markingPoints: ["Correct theorem", "Halve 80°", "Reason stated"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "maths-g12-stat-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Statistics",
    difficulty: "easy",
    marks: 2,
    cognitiveLevel: "knowledge",
    questionText: "Define the median of a data set.",
    memoAnswer: "The middle value when the data are ordered (or mean of two middle values if even n).",
    markingPoints: ["Correct definition"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-stat-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Statistics",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText: "The data set is 3; 5; 7; 7; 9; 11. Calculate the mean.",
    memoAnswer: "Mean = 42/6 = 7",
    markingPoints: ["Sum", "Divide by n", "Answer"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-prob-01",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Probability",
    difficulty: "medium",
    marks: 4,
    cognitiveLevel: "routine_procedure",
    questionText:
      "A fair six-sided die is rolled once. Calculate the probability of obtaining a prime number.",
    memoAnswer: "P = 3/6 = 1/2 (primes: 2, 3, 5)",
    markingPoints: ["Identify favourable outcomes", "Probability as fraction"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "maths-g12-prob-02",
    subject: "Mathematics",
    grade: "12",
    examBody: "DBE",
    topic: "Probability",
    difficulty: "hard",
    marks: 5,
    cognitiveLevel: "problem_solving",
    questionText:
      "Events A and B are independent with P(A) = 0,4 and P(B) = 0,5. Calculate P(A ∪ B).",
    memoAnswer: "P(A ∪ B) = 0,4 + 0,5 − 0,4×0,5 = 0,7",
    markingPoints: ["Independence → P(A∩B)=P(A)P(B)", "Addition rule", "Answer"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
];
