import type { SeedQuestion } from "./types";

/**
 * Seed Life Sciences bank (original items for MVP assembly).
 * Metadata uses Bloom levels + optional IEB AIM — not CAPS Maths cognitive levels.
 */
export const SEED_LIFE_SCIENCES_QUESTIONS: SeedQuestion[] = [
  {
    id: "ls-g12-dna-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Name the four nitrogenous bases found in DNA.",
    memoAnswer: "Adenine, thymine, cytosine, guanine",
    markingPoints: ["All four bases named"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-dna-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "medium",
    marks: 3,
    bloomLevel: "comprehension",
    aim: "aim_1",
    questionText: "Explain why DNA replication is described as semi-conservative.",
    memoAnswer:
      "Each new DNA molecule consists of one original strand and one newly synthesised strand.",
    markingPoints: ["One old + one new strand", "Clear explanation"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-dna-03",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "medium",
    marks: 4,
    bloomLevel: "application",
    aim: "aim_3",
    questionText:
      "A DNA template strand has the base sequence TAC GGA. Write the complementary mRNA sequence produced during transcription.",
    memoAnswer: "AUG CCU",
    markingPoints: ["U replaces T", "Correct base pairing", "Sequence order"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "ls-g12-dna-04",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "hard",
    marks: 6,
    bloomLevel: "analysis",
    aim: "aim_3",
    questionText:
      "Compare the roles of mRNA and tRNA in protein synthesis. Tabulate two differences.",
    memoAnswer:
      "mRNA carries the codon sequence from DNA; tRNA brings amino acids and has anticodons. mRNA is a long strand template; tRNA is clover-leaf shaped with an amino-acid attachment site.",
    markingPoints: ["Valid difference 1", "Valid difference 2", "Table or clear comparison"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "ls-g12-gen-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Define the term allele.",
    memoAnswer: "An alternative form of a gene at the same locus.",
    markingPoints: ["Correct definition"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-gen-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "medium",
    marks: 5,
    bloomLevel: "application",
    aim: "aim_3",
    questionText:
      "In pea plants, tall (T) is dominant over short (t). Cross two heterozygous tall plants. Give the phenotypic ratio of the offspring.",
    memoAnswer: "3 tall : 1 short",
    markingPoints: ["Correct Punnett / genotypes", "Phenotypic ratio"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-gen-03",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "DNA and genetics",
    difficulty: "hard",
    marks: 6,
    bloomLevel: "evaluation",
    aim: "aim_3",
    questionText:
      "A couple wants genetic counselling for a recessive disorder that runs in both families. Evaluate one benefit and one ethical concern of carrier testing before they have children.",
    memoAnswer:
      "Benefit: informed reproductive choices / early planning. Concern: privacy, discrimination, emotional impact, or pressure to terminate — any well-argued pair.",
    markingPoints: ["Valid benefit", "Valid ethical concern", "Linked to carrier testing"],
    source: "AssessMate seed bank v1",
    assessmentType: "final_exam",
    language: "en",
  },
  {
    id: "ls-g12-evo-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Evolution",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Define natural selection.",
    memoAnswer:
      "The process whereby organisms better adapted to their environment tend to survive and reproduce, passing on favourable traits.",
    markingPoints: ["Survival/reproduction of better-adapted individuals"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-evo-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Evolution",
    difficulty: "medium",
    marks: 4,
    bloomLevel: "comprehension",
    aim: "aim_1",
    questionText: "Explain the difference between homologous and analogous structures.",
    memoAnswer:
      "Homologous: similar underlying structure from common ancestry (may differ in function). Analogous: similar function but different structure / no recent common ancestry for that trait.",
    markingPoints: ["Homologous explained", "Analogous explained"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "ls-g12-evo-03",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Evolution",
    difficulty: "hard",
    marks: 6,
    bloomLevel: "analysis",
    aim: "aim_3",
    questionText:
      "Using a simple cladogram with three species, explain how shared derived characters are used to infer evolutionary relationships.",
    memoAnswer:
      "Species that share more recent derived characters are placed closer together; branching points represent common ancestors.",
    markingPoints: ["Shared derived characters", "Common ancestor / branching", "Relationship inference"],
    source: "AssessMate seed bank v1",
    assessmentType: "final_exam",
    language: "en",
  },
  {
    id: "ls-g12-evo-04",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Evolution",
    difficulty: "hard",
    marks: 8,
    bloomLevel: "synthesis",
    aim: "aim_3",
    questionText:
      "Write a short scientific argument (about 120 words) supporting the claim that fossil and genetic evidence together strengthen the case for human evolution.",
    memoAnswer:
      "Model answer should link transitional fossils / dating with DNA similarity (e.g. shared genes with other primates) and conclude that independent lines of evidence converge.",
    markingPoints: ["Fossil evidence used", "Genetic evidence used", "Coherent argument"],
    source: "AssessMate seed bank v1",
    assessmentType: "final_exam",
    language: "en",
  },
  {
    id: "ls-g12-endo-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Endocrine and nervous systems",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Name the gland that secretes insulin.",
    memoAnswer: "Pancreas (islets of Langerhans)",
    markingPoints: ["Pancreas / islets"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-endo-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Endocrine and nervous systems",
    difficulty: "medium",
    marks: 4,
    bloomLevel: "comprehension",
    aim: "aim_1",
    questionText: "Describe how insulin and glucagon work together to maintain blood glucose levels.",
    memoAnswer:
      "Insulin lowers blood glucose (promotes uptake/storage); glucagon raises blood glucose (promotes glycogen breakdown). Negative feedback keeps levels within a range.",
    markingPoints: ["Insulin action", "Glucagon action", "Homeostasis / feedback"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "ls-g12-endo-03",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Endocrine and nervous systems",
    difficulty: "hard",
    marks: 5,
    bloomLevel: "application",
    aim: "aim_3",
    questionText:
      "A learner’s blood glucose remains high despite eating little sugar. Suggest a biological explanation linked to hormone function.",
    memoAnswer:
      "Possible insulin deficiency or insulin resistance (type 1 / type 2 diabetes context) — glucose not taken up effectively by cells.",
    markingPoints: ["Hormone link", "Plausible mechanism"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "ls-g12-nerv-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Endocrine and nervous systems",
    difficulty: "medium",
    marks: 3,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "List the three main parts of a typical neuron.",
    memoAnswer: "Cell body (soma), dendrites, axon",
    markingPoints: ["Three correct parts"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-eco-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Human impact on the environment",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Define carrying capacity.",
    memoAnswer:
      "The maximum population size an environment can sustain over time given available resources.",
    markingPoints: ["Correct definition"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-eco-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Human impact on the environment",
    difficulty: "medium",
    marks: 4,
    bloomLevel: "application",
    aim: "aim_3",
    questionText:
      "Explain two ways in which overfishing can disrupt a marine food web.",
    memoAnswer:
      "Examples: removal of predators → prey population boom; removal of key prey → predator decline; bycatch affecting non-target species.",
    markingPoints: ["Valid impact 1", "Valid impact 2"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
  {
    id: "ls-g12-eco-03",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Human impact on the environment",
    difficulty: "hard",
    marks: 6,
    bloomLevel: "evaluation",
    aim: "aim_3",
    questionText:
      "Evaluate whether a community should ban single-use plastics. Give one scientific argument for and one against, then state a justified conclusion.",
    memoAnswer:
      "For: reduced pollution / wildlife harm. Against: alternatives may have higher carbon cost or hygiene issues. Conclusion must follow from the arguments.",
    markingPoints: ["Argument for", "Argument against", "Justified conclusion"],
    source: "AssessMate seed bank v1",
    assessmentType: "final_exam",
    language: "en",
  },
  {
    id: "ls-g12-cell-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Cells as basic units of life",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Name the organelle responsible for aerobic respiration in eukaryotic cells.",
    memoAnswer: "Mitochondrion / mitochondria",
    markingPoints: ["Correct organelle"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-cell-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Cells as basic units of life",
    difficulty: "medium",
    marks: 4,
    bloomLevel: "comprehension",
    aim: "aim_1",
    questionText: "Distinguish between mitosis and meiosis in terms of number of daughter cells and genetic variation.",
    memoAnswer:
      "Mitosis: two genetically identical diploid cells. Meiosis: four genetically varied haploid cells.",
    markingPoints: ["Daughter cell number", "Variation / chromosome set"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-photo-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Photosynthesis and respiration",
    difficulty: "easy",
    marks: 2,
    bloomLevel: "knowledge",
    aim: "aim_1",
    questionText: "Write the word equation for photosynthesis.",
    memoAnswer: "Carbon dioxide + water → glucose + oxygen (in the presence of light and chlorophyll)",
    markingPoints: ["Reactants", "Products", "Light/chlorophyll optional but preferred"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-photo-02",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Photosynthesis and respiration",
    difficulty: "medium",
    marks: 5,
    bloomLevel: "application",
    aim: "aim_2",
    questionText:
      "Describe a simple experiment to show that light is needed for photosynthesis. Include one control.",
    memoAnswer:
      "Cover part of a leaf / keep plant in dark vs light; test for starch with iodine. Control: uncovered leaf / plant in light.",
    markingPoints: ["Method involving light vs no light", "Starch test", "Control stated"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-trans-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Support and transport in animals",
    difficulty: "medium",
    marks: 3,
    bloomLevel: "comprehension",
    aim: "aim_1",
    questionText: "Explain why arteries have thicker muscular walls than veins.",
    memoAnswer:
      "Arteries carry blood at higher pressure from the heart; thicker walls withstand and help maintain pressure.",
    markingPoints: ["Higher pressure link", "Structural reason"],
    source: "AssessMate seed bank v1",
    assessmentType: "cycle_test",
    language: "en",
  },
  {
    id: "ls-g12-bio-01",
    subject: "Life Sciences",
    grade: "12",
    examBody: "IEB",
    topic: "Biodiversity and classification",
    difficulty: "medium",
    marks: 4,
    bloomLevel: "analysis",
    aim: "aim_3",
    questionText:
      "Two species look similar but cannot produce fertile offspring. Justify classifying them as separate species using the biological species concept.",
    memoAnswer:
      "Biological species concept: groups that can interbreed to produce fertile offspring. Inability to do so means they are separate species.",
    markingPoints: ["State concept", "Apply to infertile/no offspring case"],
    source: "AssessMate seed bank v1",
    assessmentType: "june_exam",
    language: "en",
  },
];
